### ISSUE TITLE
Nouns pointing to VSBST-EVEN and Der/ahtes (

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-smj#86]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2588
Date: 2019-05-21T09:57:54+02:00
From: Sjur Nørstebø Moshagen &lt;<sjur.n.moshagen>&gt;
To:   Elena Junie Paulsen &lt;<elena.j.paulsen>&gt;
CC:   elena.j.paulsen, lene.antonsen, sjur.n.moshagen, thomas.omma, trond.trosterud

Last updated: 2019-05-21T10:45:16+02:00

**Comment by albbas** [comment]
## Comment 13432
Date: 2019-05-21 10:45:16 +0200
From: Lene Antonsen &lt;<lene.antonsen>&gt;

Her er adjektivene som er leksikaliserte i LEXC (de får alle +Der/NomAct+N+Der/ahtes som analyse):

buorránahtes
duhtamahtes
dádjadahtes
dåbddåmahtes
dåbddåmahtes
dåhkkimahtes
gierddamahtes
huomajahtes
oahppamahtes
sárnnomahtes
såbadahtes
såbadahtes
såbadahtes
vielldemahtes
vuojnnemahtes
årodahtes
åskeldahtes

**Comment by ilm024** [comment]
-ahtes derivation is only possible on odd nouns and NomAct from even verbs (becoming even nouns) (bårråt>bårråm>bårråmahtes).  So i have removed (outcommented) this -ahtes derivation from VSBST-EVEN.

-ahtes derivation can also be added to odd verbs, "Buorránahtes" is derivation from "buorránit", not buorránibme. (I might add this derivation to odd-syll verbs, but with +Use/NG, since it isn't very productive.
